### ISSUE TITLE
_configure() got an unexpected keyword argument

### ISSUE THREAD

**Issue by jomyhuang** [tambetm/gym-minecraft#1]
Hello,
after I installed minecraft-py, launch minecraft is ok. but, run examples/test.py or others code always got _configure() got an unexpected keyword argument:

python test.py
[2017-01-10 10:30:28,995] Making new env: MinecraftBasic-v0
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    env.configure(allowDiscreteMovement=["move", "turn"], log_level="INFO")
  File "/Users/jomyhuang/Desktop/dev/gym/gym/core.py", line 230, in configure
    reraise(suffix='(for {})'.format(self.spec.id))
  File "/Users/jomyhuang/Desktop/dev/gym/gym/utils/reraise.py", line 17, in reraise
    reraise_impl(e, traceback)
  File "/Users/jomyhuang/Desktop/dev/gym/gym/core.py", line 224, in configure
    self._configure(*args, **kwargs)
gym.utils.reraise.ReraisedException: The original exception was:

exceptions.TypeError: _configure() got an unexpected keyword argument 'allowDiscreteMovement'

(for MinecraftBasic-v0)

**Comment by tambetm** [comment]
Oh, due to recent change in Gym, I had to rename `configure()` to `init()`. Sorry, haven't had time to update examples and documentation yet. Plus it seems they are going to revert this change, so probably I will change it back to `configure()` soon!

**Comment by jomyhuang** [comment]
got it! thank you!
